version: '2'
services:
    boatal-app:
        image: boatal
        external_links:
            - boatal-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/Boatal
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    boatal-postgresql:
        extends:
            file: postgresql.yml
            service: boatal-postgresql
