version: '2'
services:
    boatal-postgresql:
        container_name: boatal-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/Boatal/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=Boatal
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
